import { CourtCase } from '@/types/courtCase';

export const mockCourtCases: CourtCase[] = [
  {
    id: '1',
    caseTitle: 'Save Deities Temple vs Municipal Corporation',
    caseNumber: 'CWP-2024-001',
    description: 'Petition challenging the demolition notice issued by the municipal corporation for the ancient temple premises.',
    dateFiled: '2024-01-15',
    status: 'Active',
    courtName: 'High Court of Justice',
    judgeName: 'Hon. Justice R.K. Sharma',
    plaintiff: 'Save Deities Temple Trust',
    defendant: 'Municipal Corporation',
    caseType: 'Civil Writ Petition',
    priority: 'High',
    pdfFileUrl: 'https://example.com/case1.pdf',
    pdfFileName: 'Petition_CWP-2024-001.pdf',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: '2',
    caseTitle: 'Heritage Protection Appeal',
    caseNumber: 'SLP-2024-002',
    description: 'Special Leave Petition for protection of heritage temple structure and surrounding archaeological sites.',
    dateFiled: '2024-02-20',
    status: 'Pending',
    courtName: 'Supreme Court of India',
    judgeName: 'Hon. Justice M.L. Verma',
    plaintiff: 'Heritage Conservation Society',
    defendant: 'State Government',
    caseType: 'Special Leave Petition',
    priority: 'High',
    pdfFileUrl: 'https://example.com/case2.pdf',
    pdfFileName: 'SLP_Heritage_Protection.pdf',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: '3',
    caseTitle: 'Land Acquisition Compensation',
    caseNumber: 'CA-2024-003',
    description: 'Appeal for fair compensation for temple land acquired for public infrastructure development.',
    dateFiled: '2024-03-10',
    status: 'Closed',
    courtName: 'District Court',
    judgeName: 'Hon. Justice S.P. Singh',
    plaintiff: 'Temple Management Committee',
    defendant: 'Land Acquisition Officer',
    caseType: 'Civil Appeal',
    priority: 'Medium',
    pdfFileUrl: 'https://example.com/case3.pdf',
    pdfFileName: 'Land_Compensation_Appeal.pdf',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: '4',
    caseTitle: 'Religious Freedom Protection',
    caseNumber: 'PIL-2024-004',
    description: 'Public Interest Litigation for protection of religious practices and freedom of worship at the temple.',
    dateFiled: '2024-04-05',
    status: 'Active',
    courtName: 'High Court of Justice',
    judgeName: 'Hon. Justice A.K. Gupta',
    plaintiff: 'Citizens for Religious Freedom',
    defendant: 'State of Delhi',
    caseType: 'Public Interest Litigation',
    priority: 'High',
    pdfFileUrl: 'https://example.com/case4.pdf',
    pdfFileName: 'Religious_Freedom_PIL.pdf',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-12-12'),
  },
  {
    id: '5',
    caseTitle: 'Environmental Clearance Challenge',
    caseNumber: 'NGT-2024-005',
    description: 'Challenge to environmental clearance granted for construction activities near the temple complex.',
    dateFiled: '2024-05-18',
    status: 'Pending',
    courtName: 'National Green Tribunal',
    judgeName: 'Hon. Justice Environmental Panel',
    plaintiff: 'Environmental Protection Group',
    defendant: 'Project Developer',
    caseType: 'Environmental Appeal',
    priority: 'Medium',
    createdAt: new Date('2024-05-18'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: '6',
    caseTitle: 'Archaeological Survey Dispute',
    caseNumber: 'WP-2024-006',
    description: 'Writ petition regarding archaeological survey findings and their impact on temple operations.',
    dateFiled: '2024-06-22',
    status: 'Active',
    courtName: 'High Court of Justice',
    judgeName: 'Hon. Justice Cultural Heritage Bench',
    plaintiff: 'Archaeological Society',
    defendant: 'Archaeological Survey of India',
    caseType: 'Writ Petition',
    priority: 'Low',
    pdfFileUrl: 'https://example.com/case6.pdf',
    pdfFileName: 'Archaeological_Survey_Dispute.pdf',
    createdAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-11-30'),
  },
];